// <auto-generated />
using System;
using BlogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Migrations
{
    [DbContext(typeof(BlogAppDbContext))]
    [Migration("20230428020608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogApp.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is my first post.",
                            CreatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2215),
                            Title = "First Post",
                            UpdatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2259)
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is my second post.",
                            CreatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2271),
                            Title = "Second Post",
                            UpdatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2274)
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is my third post.",
                            CreatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2279),
                            Title = "Third Post",
                            UpdatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2282)
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is my fourth post.",
                            CreatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2285),
                            Title = "Fourth Post",
                            UpdatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2288)
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is my fifth post.",
                            CreatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2292),
                            Title = "Fifth Post",
                            UpdatedAt = new DateTime(2023, 4, 27, 19, 6, 7, 988, DateTimeKind.Local).AddTicks(2295)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
