// <auto-generated />
using System;
using BlogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Migrations
{
    [DbContext(typeof(BlogAppDbContext))]
    [Migration("20230528204531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogApp.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Content for post 1",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6265),
                            Title = "Post 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6305)
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Content for post 2",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6318),
                            Title = "Post 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6322)
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Content for post 3",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6328),
                            Title = "Post 3",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6331)
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Content for post 4",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6336),
                            Title = "Post 4",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Content for post 5",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6345),
                            Title = "Post 5",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6348)
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Content for post 6",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6357),
                            Title = "Post 6",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6361)
                        },
                        new
                        {
                            PostId = 7,
                            Content = "Content for post 7",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6367),
                            Title = "Post 7",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6370)
                        },
                        new
                        {
                            PostId = 8,
                            Content = "Content for post 8",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6375),
                            Title = "Post 8",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6378)
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Content for post 9",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6383),
                            Title = "Post 9",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6386)
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Content for post 10",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6395),
                            Title = "Post 10",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6399)
                        },
                        new
                        {
                            PostId = 11,
                            Content = "Content for post 11",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6405),
                            Title = "Post 11",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6408)
                        },
                        new
                        {
                            PostId = 12,
                            Content = "Content for post 12",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6414),
                            Title = "Post 12",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6417)
                        },
                        new
                        {
                            PostId = 13,
                            Content = "Content for post 13",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6423),
                            Title = "Post 13",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6426)
                        },
                        new
                        {
                            PostId = 14,
                            Content = "Content for post 14",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6431),
                            Title = "Post 14",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6434)
                        },
                        new
                        {
                            PostId = 15,
                            Content = "Content for post 15",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6440),
                            Title = "Post 15",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6443)
                        },
                        new
                        {
                            PostId = 16,
                            Content = "Content for post 16",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6449),
                            Title = "Post 16",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6452)
                        },
                        new
                        {
                            PostId = 17,
                            Content = "Content for post 17",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6457),
                            Title = "Post 17",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6460)
                        },
                        new
                        {
                            PostId = 18,
                            Content = "Content for post 18",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6469),
                            Title = "Post 18",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6473)
                        },
                        new
                        {
                            PostId = 19,
                            Content = "Content for post 19",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6479),
                            Title = "Post 19",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6482)
                        },
                        new
                        {
                            PostId = 20,
                            Content = "Content for post 20",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6488),
                            Title = "Post 20",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6491)
                        },
                        new
                        {
                            PostId = 21,
                            Content = "Content for post 21",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6497),
                            Title = "Post 21",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6500)
                        },
                        new
                        {
                            PostId = 22,
                            Content = "Content for post 22",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6506),
                            Title = "Post 22",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6509)
                        },
                        new
                        {
                            PostId = 23,
                            Content = "Content for post 23",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6514),
                            Title = "Post 23",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6517)
                        },
                        new
                        {
                            PostId = 24,
                            Content = "Content for post 24",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6523),
                            Title = "Post 24",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6526)
                        },
                        new
                        {
                            PostId = 25,
                            Content = "Content for post 25",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6532),
                            Title = "Post 25",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6535)
                        },
                        new
                        {
                            PostId = 26,
                            Content = "Content for post 26",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6540),
                            Title = "Post 26",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6543)
                        },
                        new
                        {
                            PostId = 27,
                            Content = "Content for post 27",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6549),
                            Title = "Post 27",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6552)
                        },
                        new
                        {
                            PostId = 28,
                            Content = "Content for post 28",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6557),
                            Title = "Post 28",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6560)
                        },
                        new
                        {
                            PostId = 29,
                            Content = "Content for post 29",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6566),
                            Title = "Post 29",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6569)
                        },
                        new
                        {
                            PostId = 30,
                            Content = "Content for post 30",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6574),
                            Title = "Post 30",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6577)
                        },
                        new
                        {
                            PostId = 31,
                            Content = "Content for post 31",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6583),
                            Title = "Post 31",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6586)
                        },
                        new
                        {
                            PostId = 32,
                            Content = "Content for post 32",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6591),
                            Title = "Post 32",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6594)
                        },
                        new
                        {
                            PostId = 33,
                            Content = "Content for post 33",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6722),
                            Title = "Post 33",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6728)
                        },
                        new
                        {
                            PostId = 34,
                            Content = "Content for post 34",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 34",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6744)
                        },
                        new
                        {
                            PostId = 35,
                            Content = "Content for post 35",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6749),
                            Title = "Post 35",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            PostId = 36,
                            Content = "Content for post 36",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6758),
                            Title = "Post 36",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6761)
                        },
                        new
                        {
                            PostId = 37,
                            Content = "Content for post 37",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6766),
                            Title = "Post 37",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6769)
                        },
                        new
                        {
                            PostId = 38,
                            Content = "Content for post 38",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6775),
                            Title = "Post 38",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6778)
                        },
                        new
                        {
                            PostId = 39,
                            Content = "Content for post 39",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6783),
                            Title = "Post 39",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6786)
                        },
                        new
                        {
                            PostId = 40,
                            Content = "Content for post 40",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6792),
                            Title = "Post 40",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6795)
                        },
                        new
                        {
                            PostId = 41,
                            Content = "Content for post 41",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6800),
                            Title = "Post 41",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6803)
                        },
                        new
                        {
                            PostId = 42,
                            Content = "Content for post 42",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6808),
                            Title = "Post 42",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6811)
                        },
                        new
                        {
                            PostId = 43,
                            Content = "Content for post 43",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6817),
                            Title = "Post 43",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6820)
                        },
                        new
                        {
                            PostId = 44,
                            Content = "Content for post 44",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6825),
                            Title = "Post 44",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6828)
                        },
                        new
                        {
                            PostId = 45,
                            Content = "Content for post 45",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6833),
                            Title = "Post 45",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6836)
                        },
                        new
                        {
                            PostId = 46,
                            Content = "Content for post 46",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6841),
                            Title = "Post 46",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6844)
                        },
                        new
                        {
                            PostId = 47,
                            Content = "Content for post 47",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6849),
                            Title = "Post 47",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6852)
                        },
                        new
                        {
                            PostId = 48,
                            Content = "Content for post 48",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6857),
                            Title = "Post 48",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6860)
                        },
                        new
                        {
                            PostId = 49,
                            Content = "Content for post 49",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6866),
                            Title = "Post 49",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6868)
                        },
                        new
                        {
                            PostId = 50,
                            Content = "Content for post 50",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6874),
                            Title = "Post 50",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6876)
                        },
                        new
                        {
                            PostId = 51,
                            Content = "Content for post 51",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6882),
                            Title = "Post 51",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6885)
                        },
                        new
                        {
                            PostId = 52,
                            Content = "Content for post 52",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6890),
                            Title = "Post 52",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6893)
                        },
                        new
                        {
                            PostId = 53,
                            Content = "Content for post 53",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6898),
                            Title = "Post 53",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6901)
                        },
                        new
                        {
                            PostId = 54,
                            Content = "Content for post 54",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6906),
                            Title = "Post 54",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6909)
                        },
                        new
                        {
                            PostId = 55,
                            Content = "Content for post 55",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6914),
                            Title = "Post 55",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6917)
                        },
                        new
                        {
                            PostId = 56,
                            Content = "Content for post 56",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6923),
                            Title = "Post 56",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6926)
                        },
                        new
                        {
                            PostId = 57,
                            Content = "Content for post 57",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6931),
                            Title = "Post 57",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6934)
                        },
                        new
                        {
                            PostId = 58,
                            Content = "Content for post 58",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6939),
                            Title = "Post 58",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6942)
                        },
                        new
                        {
                            PostId = 59,
                            Content = "Content for post 59",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6947),
                            Title = "Post 59",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6950)
                        },
                        new
                        {
                            PostId = 60,
                            Content = "Content for post 60",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6955),
                            Title = "Post 60",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6958)
                        },
                        new
                        {
                            PostId = 61,
                            Content = "Content for post 61",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6963),
                            Title = "Post 61",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6966)
                        },
                        new
                        {
                            PostId = 62,
                            Content = "Content for post 62",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6971),
                            Title = "Post 62",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6974)
                        },
                        new
                        {
                            PostId = 63,
                            Content = "Content for post 63",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6979),
                            Title = "Post 63",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6982)
                        },
                        new
                        {
                            PostId = 64,
                            Content = "Content for post 64",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6988),
                            Title = "Post 64",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6990)
                        },
                        new
                        {
                            PostId = 65,
                            Content = "Content for post 65",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6996),
                            Title = "Post 65",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(6999)
                        },
                        new
                        {
                            PostId = 66,
                            Content = "Content for post 66",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7007),
                            Title = "Post 66",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7011)
                        },
                        new
                        {
                            PostId = 67,
                            Content = "Content for post 67",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7016),
                            Title = "Post 67",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7019)
                        },
                        new
                        {
                            PostId = 68,
                            Content = "Content for post 68",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7025),
                            Title = "Post 68",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7028)
                        },
                        new
                        {
                            PostId = 69,
                            Content = "Content for post 69",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7033),
                            Title = "Post 69",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7036)
                        },
                        new
                        {
                            PostId = 70,
                            Content = "Content for post 70",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7041),
                            Title = "Post 70",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7044)
                        },
                        new
                        {
                            PostId = 71,
                            Content = "Content for post 71",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7049),
                            Title = "Post 71",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7052)
                        },
                        new
                        {
                            PostId = 72,
                            Content = "Content for post 72",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7057),
                            Title = "Post 72",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7060)
                        },
                        new
                        {
                            PostId = 73,
                            Content = "Content for post 73",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7065),
                            Title = "Post 73",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7068)
                        },
                        new
                        {
                            PostId = 74,
                            Content = "Content for post 74",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7120),
                            Title = "Post 74",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7125)
                        },
                        new
                        {
                            PostId = 75,
                            Content = "Content for post 75",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7132),
                            Title = "Post 75",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7135)
                        },
                        new
                        {
                            PostId = 76,
                            Content = "Content for post 76",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7141),
                            Title = "Post 76",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7145)
                        },
                        new
                        {
                            PostId = 77,
                            Content = "Content for post 77",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7151),
                            Title = "Post 77",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7154)
                        },
                        new
                        {
                            PostId = 78,
                            Content = "Content for post 78",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7159),
                            Title = "Post 78",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7162)
                        },
                        new
                        {
                            PostId = 79,
                            Content = "Content for post 79",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7168),
                            Title = "Post 79",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7171)
                        },
                        new
                        {
                            PostId = 80,
                            Content = "Content for post 80",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7176),
                            Title = "Post 80",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7179)
                        },
                        new
                        {
                            PostId = 81,
                            Content = "Content for post 81",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7185),
                            Title = "Post 81",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7188)
                        },
                        new
                        {
                            PostId = 82,
                            Content = "Content for post 82",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7193),
                            Title = "Post 82",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7196)
                        },
                        new
                        {
                            PostId = 83,
                            Content = "Content for post 83",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7202),
                            Title = "Post 83",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7205)
                        },
                        new
                        {
                            PostId = 84,
                            Content = "Content for post 84",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7210),
                            Title = "Post 84",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7213)
                        },
                        new
                        {
                            PostId = 85,
                            Content = "Content for post 85",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7219),
                            Title = "Post 85",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7222)
                        },
                        new
                        {
                            PostId = 86,
                            Content = "Content for post 86",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7227),
                            Title = "Post 86",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7230)
                        },
                        new
                        {
                            PostId = 87,
                            Content = "Content for post 87",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7236),
                            Title = "Post 87",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7239)
                        },
                        new
                        {
                            PostId = 88,
                            Content = "Content for post 88",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7245),
                            Title = "Post 88",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7248)
                        },
                        new
                        {
                            PostId = 89,
                            Content = "Content for post 89",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7253),
                            Title = "Post 89",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7256)
                        },
                        new
                        {
                            PostId = 90,
                            Content = "Content for post 90",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7262),
                            Title = "Post 90",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7265)
                        },
                        new
                        {
                            PostId = 91,
                            Content = "Content for post 91",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7270),
                            Title = "Post 91",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7273)
                        },
                        new
                        {
                            PostId = 92,
                            Content = "Content for post 92",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7279),
                            Title = "Post 92",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7282)
                        },
                        new
                        {
                            PostId = 93,
                            Content = "Content for post 93",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7287),
                            Title = "Post 93",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7290)
                        },
                        new
                        {
                            PostId = 94,
                            Content = "Content for post 94",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7296),
                            Title = "Post 94",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7299)
                        },
                        new
                        {
                            PostId = 95,
                            Content = "Content for post 95",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7304),
                            Title = "Post 95",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7307)
                        },
                        new
                        {
                            PostId = 96,
                            Content = "Content for post 96",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7313),
                            Title = "Post 96",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7316)
                        },
                        new
                        {
                            PostId = 97,
                            Content = "Content for post 97",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7321),
                            Title = "Post 97",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7324)
                        },
                        new
                        {
                            PostId = 98,
                            Content = "Content for post 98",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7330),
                            Title = "Post 98",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7333)
                        },
                        new
                        {
                            PostId = 99,
                            Content = "Content for post 99",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7338),
                            Title = "Post 99",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7341)
                        },
                        new
                        {
                            PostId = 100,
                            Content = "Content for post 100",
                            CreatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7347),
                            Title = "Post 100",
                            UpdatedAt = new DateTime(2023, 5, 28, 13, 45, 31, 570, DateTimeKind.Local).AddTicks(7350)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
